# Generated by Django 5.2.1 on 2025-10-14 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_userprofile_city_state_userprofile_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications', verbose_name='email notifications')),
                ('push_notifications', models.BooleanField(default=True, help_text='Receive push notifications', verbose_name='push notifications')),
                ('in_app_notifications', models.BooleanField(default=True, help_text='Receive in-app notifications', verbose_name='in-app notifications')),
                ('project_updates', models.BooleanField(default=True, help_text='Receive project update notifications', verbose_name='project updates')),
                ('security_alerts', models.BooleanField(default=True, help_text='Receive security alert notifications', verbose_name='security alerts')),
                ('social_activities', models.BooleanField(default=True, help_text='Receive social activity notifications', verbose_name='social activities')),
                ('system_messages', models.BooleanField(default=True, help_text='Receive system message notifications', verbose_name='system messages')),
                ('notification_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('hourly', 'Hourly Digest'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='immediate', max_length=20, verbose_name='notification frequency')),
                ('notification_sound', models.BooleanField(default=True, help_text='Play sound for notifications', verbose_name='notification sound')),
                ('desktop_notifications', models.BooleanField(default=True, help_text='Show desktop notifications', verbose_name='desktop notifications')),
                ('mobile_notifications', models.BooleanField(default=True, help_text='Send mobile push notifications', verbose_name='mobile notifications')),
                ('do_not_disturb', models.BooleanField(default=False, help_text='Enable do not disturb mode', verbose_name='do not disturb')),
                ('do_not_disturb_start', models.TimeField(blank=True, help_text='Do not disturb start time', null=True, verbose_name='do not disturb start')),
                ('do_not_disturb_end', models.TimeField(blank=True, help_text='Do not disturb end time', null=True, verbose_name='do not disturb end')),
                ('keep_notification_history', models.BooleanField(default=True, help_text='Keep history of notifications', verbose_name='keep notification history')),
                ('auto_clear_read', models.BooleanField(default=False, help_text='Automatically clear read notifications', verbose_name='auto clear read notifications')),
                ('history_retention_days', models.IntegerField(default=30, help_text='Number of days to keep notification history', verbose_name='history retention days')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Notifications',
                'verbose_name_plural': 'Notifications',
                'db_table': 'user_notifications',
            },
        ),
    ]
