# Generated by Django 5.2.1 on 2025-10-14 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='The actual message content', verbose_name='message content')),
                ('notification_type', models.CharField(choices=[('project', 'Project'), ('system', 'System'), ('security', 'Security'), ('social', 'Social'), ('general', 'General')], default='general', max_length=20, verbose_name='notification type')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='sent', max_length=20, verbose_name='message status')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read by the receiver', verbose_name='is read')),
                ('action', models.CharField(blank=True, help_text='Action that triggered this notification', max_length=100, verbose_name='action')),
                ('project', models.CharField(blank=True, help_text='Related project name', max_length=100, verbose_name='project')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('parent_notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='auth_app.notification', verbose_name='parent notification')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL, verbose_name='receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications', verbose_name='email notifications')),
                ('push_notifications', models.BooleanField(default=True, help_text='Receive push notifications', verbose_name='push notifications')),
                ('in_app_notifications', models.BooleanField(default=True, help_text='Receive in-app notifications', verbose_name='in-app notifications')),
                ('project_updates', models.BooleanField(default=True, help_text='Receive project update notifications', verbose_name='project updates')),
                ('security_alerts', models.BooleanField(default=True, help_text='Receive security alert notifications', verbose_name='security alerts')),
                ('social_activities', models.BooleanField(default=True, help_text='Receive social activity notifications', verbose_name='social activities')),
                ('system_messages', models.BooleanField(default=True, help_text='Receive system message notifications', verbose_name='system messages')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User Notification Settings',
                'verbose_name_plural': 'User Notification Settings',
                'db_table': 'user_notification_settings',
            },
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['sender', 'receiver'], name='notificatio_sender__49b019_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['receiver', 'is_read'], name='notificatio_receive_21f75c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'),
        ),
    ]
