# Generated by Django 5.2.1 on 2025-10-14 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_notification_usernotificationsettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotificationsettings',
            name='user',
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, help_text='Auto-generated username from user model', max_length=150, verbose_name='username')),
                ('firstname', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('message', models.TextField(help_text='User message content', max_length=1000, verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='edited at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='UserNotificationSettings',
        ),
    ]
