# Generated by Django 5.2.1 on 2025-10-14 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_remove_usernotificationsettings_user_messages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='email',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='user',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='username',
        ),
        migrations.AddField(
            model_name='messages',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='read status'),
        ),
        migrations.AddField(
            model_name='messages',
            name='receiver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='receiver'),
        ),
        migrations.AddField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='sender'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.TextField(help_text='User message content', max_length=1000, verbose_name='message content'),
        ),
    ]
