# Generated by Django 5.2.1 on 2025-10-17 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0015_message_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('pastor_name', models.CharField(max_length=100)),
                ('number_churches', models.PositiveIntegerField(default=0)),
                ('number_collages', models.PositiveIntegerField(default=0)),
                ('total_members', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['name'],
            },
        ),
    ]
