# Generated by Django 5.2.1 on 2025-10-18 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0017_church'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churches', to='auth_app.district'),
        ),
    ]
