# Generated by Django 5.2.1 on 2025-10-18 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0018_alter_church_district'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={},
        ),
        migrations.RemoveField(
            model_name='church',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='church',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='church',
            name='church_name',
            field=models.CharField(help_text='Enter the official church name (must be unique)', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Enter a valid email address for contact', max_length=254),
        ),
        migrations.AlterField(
            model_name='church',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Enter phone number with country code', max_length=20),
        ),
        migrations.AlterField(
            model_name='church',
            name='date_established',
            field=models.DateField(blank=True, help_text='Select the date when this church was established', null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='district',
            field=models.ForeignKey(help_text='Select the district this church belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='churches', to='auth_app.district'),
        ),
        migrations.AlterField(
            model_name='church',
            name='location',
            field=models.CharField(blank=True, help_text='Enter the physical address or location', max_length=255),
        ),
        migrations.AlterField(
            model_name='church',
            name='members',
            field=models.PositiveIntegerField(default=0, help_text='Current number of active members'),
        ),
        migrations.AlterField(
            model_name='church',
            name='total_members',
            field=models.PositiveIntegerField(default=0, help_text='Total members including inactive (auto-corrected to be ≥ active members)'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(help_text='Enter the district name (must be unique)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='number_churches',
            field=models.PositiveIntegerField(default=0, help_text='Auto-calculated: Number of churches in this district'),
        ),
        migrations.AlterField(
            model_name='district',
            name='number_collages',
            field=models.PositiveIntegerField(default=0, help_text='Enter the number of colleges in this district'),
        ),
        migrations.AlterField(
            model_name='district',
            name='pastor_name',
            field=models.CharField(help_text="Enter the pastor's full name", max_length=100),
        ),
        migrations.AlterField(
            model_name='district',
            name='total_members',
            field=models.PositiveIntegerField(default=0, help_text='Auto-calculated: Total members across all churches'),
        ),
    ]
