# Generated by Django 5.2.1 on 2025-10-18 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0019_alter_church_options_alter_district_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={'ordering': ['church_name'], 'verbose_name_plural': 'Churches'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name']},
        ),
    ]
