# Generated by Django 5.2.1 on 2025-10-19 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0020_alter_church_options_alter_district_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, help_text="Enter the member's middle name (optional)", max_length=100)),
                ('mobile_number', models.CharField(blank=True, help_text='Enter mobile number', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Upload a profile picture for the member', null=True, upload_to='members/images/')),
                ('date_joined', models.DateField(auto_now_add=True, help_text='Date when this member record was created')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this member is currently active')),
                ('church', models.OneToOneField(help_text='Select the church this member belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='member', to='auth_app.church')),
                ('user', models.OneToOneField(help_text='Select the user account for this member', on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Members',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
