# Generated by Django 5.2.1 on 2025-10-19 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0021_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='church_name',
            field=models.CharField(help_text='Enter the official church name (must be unique)', max_length=200),
        ),
        migrations.AlterField(
            model_name='members',
            name='church',
            field=models.ForeignKey(help_text='Select the church this member belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='members_set', to='auth_app.church'),
        ),
        migrations.AddConstraint(
            model_name='members',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_membership'),
        ),
    ]
