# Generated by Django 5.2.1 on 2025-10-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0022_alter_church_church_name_alter_members_church_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', help_text='Select the role for this member', max_length=20),
        ),
    ]
