# Generated by Django 5.2.1 on 2025-10-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0023_members_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', help_text='Indicates whether the data is monthly, quarterly or annually.', max_length=10)),
                ('period_label', models.CharField(help_text="Display label like 'Jan', 'Q1', or '2024'.", max_length=20)),
                ('period_date', models.DateField(help_text='Reference date (e.g., Jan 1 for January, first day of quarter/year).')),
                ('donations_received', models.DecimalField(decimal_places=2, help_text='Total donations received during this period.', max_digits=12)),
                ('funds_distributed', models.DecimalField(decimal_places=2, help_text='Total funds distributed during this period.', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Charity Performance',
                'verbose_name_plural': 'Charity Performances',
                'ordering': ['period_date'],
            },
        ),
    ]
