# Generated by Django 5.2.1 on 2025-10-21 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0025_alter_charityperformance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charityperformance',
            options={'verbose_name': 'Charity Performance', 'verbose_name_plural': 'Charity Performance Records'},
        ),
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collage_name', models.CharField(max_length=200)),
                ('total_members', models.IntegerField(default=0)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collages', to='auth_app.district')),
            ],
        ),
    ]
