# Generated by Django 5.2.1 on 2025-10-21 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0026_alter_charityperformance_options_collage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollageMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(choices=[('tanzania', 'Tanzania'), ('kenya', 'Kenya'), ('uganda', 'Uganda'), ('rwanda', 'Rwanda'), ('burundi', 'Burundi'), ('other', 'Other')], default='tanzania', max_length=20)),
                ('region', models.CharField(blank=True, choices=[('arusha', 'Arusha'), ('dar_es_salaam', 'Dar es Salaam'), ('dodoma', 'Dodoma'), ('geita', 'Geita'), ('iringa', 'Iringa'), ('kagera', 'Kagera'), ('katavi', 'Katavi'), ('kigoma', 'Kigoma'), ('kilimanjaro', 'Kilimanjaro'), ('lindi', 'Lindi'), ('manyara', 'Manyara'), ('mara', 'Mara'), ('mbeya', 'Mbeya'), ('morogoro', 'Morogoro'), ('mtwara', 'Mtwara'), ('mwanza', 'Mwanza'), ('njombe', 'Njombe'), ('pemba_north', 'Pemba North'), ('pemba_south', 'Pemba South'), ('pwani', 'Pwani'), ('rukwa', 'Rukwa'), ('ruvuma', 'Ruvuma'), ('shinyanga', 'Shinyanga'), ('simiyu', 'Simiyu'), ('singida', 'Singida'), ('songwe', 'Songwe'), ('tabora', 'Tabora'), ('tanga', 'Tanga'), ('zanzibar_north', 'Zanzibar North'), ('zanzibar_south', 'Zanzibar South'), ('zanzibar_west', 'Zanzibar West')], max_length=50, null=True)),
                ('date_of_birth', models.DateField()),
                ('education_level', models.CharField(choices=[('first_year', 'First Year'), ('second_year', 'Second Year'), ('third_year', 'Third Year'), ('fourth_year', 'Fourth Year'), ('fifth_year', 'Fifth Year'), ('sixth_year', 'Sixth Year')], max_length=20)),
                ('your_course', models.CharField(max_length=200)),
                ('your_origin_church', models.CharField(max_length=200)),
                ('your_origin_district', models.CharField(max_length=200)),
                ('your_secretary_name', models.CharField(max_length=200)),
                ('your_elder_from', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collage_members', to='auth_app.church')),
                ('collage_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='auth_app.collage')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collage_members', to='auth_app.district')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collage_member_profile', to='auth_app.members')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collage_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collage Member',
                'verbose_name_plural': 'Collage Members',
                'ordering': ['-created_at'],
            },
        ),
    ]
