# Generated by Django 5.2.1 on 2025-10-21 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0027_collagemembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the church calendar event/document', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the calendar', null=True)),
                ('document', models.FileField(help_text='Upload calendar document (PDF, Word, Excel, etc.)', upload_to='calendars/church/')),
                ('year', models.CharField(help_text='e.g., 2024', max_length=10)),
                ('start_date', models.DateField(help_text='Calendar start date')),
                ('end_date', models.DateField(help_text='Calendar end date')),
                ('is_active', models.BooleanField(default=True, help_text='Is this calendar currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(help_text='Select the church this calendar belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='auth_app.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_church_calendars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Church Calendar',
                'verbose_name_plural': 'Church Calendars',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChurchTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the church timetable', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the timetable', null=True)),
                ('document', models.FileField(help_text='Upload timetable document (PDF, Word, Excel, etc.)', upload_to='timetables/church/')),
                ('period', models.CharField(help_text='e.g., Weekly, Monthly, Quarterly, Annual', max_length=50)),
                ('start_date', models.DateField(help_text='Timetable start date')),
                ('end_date', models.DateField(help_text='Timetable end date')),
                ('is_active', models.BooleanField(default=True, help_text='Is this timetable currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(help_text='Select the church this timetable belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='auth_app.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_church_timetables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Church Timetable',
                'verbose_name_plural': 'Church Timetables',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollageCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the calendar event/document', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the calendar', null=True)),
                ('document', models.FileField(help_text='Upload calendar document (PDF, Word, Excel, etc.)', upload_to='calendars/collage/')),
                ('academic_year', models.CharField(help_text='e.g., 2024/2025', max_length=20)),
                ('start_date', models.DateField(help_text='Calendar start date')),
                ('end_date', models.DateField(help_text='Calendar end date')),
                ('is_active', models.BooleanField(default=True, help_text='Is this calendar currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collage_calendars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collage Calendar',
                'verbose_name_plural': 'Collage Calendars',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollageTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the timetable', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the timetable', null=True)),
                ('document', models.FileField(help_text='Upload timetable document (PDF, Word, Excel, etc.)', upload_to='timetables/collage/')),
                ('start_date', models.DateField(help_text='Timetable start date')),
                ('end_date', models.DateField(help_text='Timetable end date')),
                ('is_active', models.BooleanField(default=True, help_text='Is this timetable currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collage', models.ForeignKey(help_text='Select the collage this timetable belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='auth_app.collage')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collage_timetables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collage Timetable',
                'verbose_name_plural': 'Collage Timetables',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DistrictCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the district calendar event/document', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the calendar', null=True)),
                ('document', models.FileField(help_text='Upload calendar document (PDF, Word, Excel, etc.)', upload_to='calendars/district/')),
                ('year', models.CharField(help_text='e.g., 2024', max_length=10)),
                ('start_date', models.DateField(help_text='Calendar start date')),
                ('end_date', models.DateField(help_text='Calendar end date')),
                ('is_active', models.BooleanField(default=True, help_text='Is this calendar currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_district_calendars', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(help_text='Select the district this calendar belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='auth_app.district')),
            ],
            options={
                'verbose_name': 'District Calendar',
                'verbose_name_plural': 'District Calendars',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DistrictTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the district timetable', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the timetable', null=True)),
                ('document', models.FileField(help_text='Upload timetable document (PDF, Word, Excel, etc.)', upload_to='timetables/district/')),
                ('period', models.CharField(help_text='e.g., Weekly, Monthly, Quarterly, Annual', max_length=50)),
                ('start_date', models.DateField(help_text='Timetable start date')),
                ('end_date', models.DateField(help_text='Timetable end date')),
                ('is_active', models.BooleanField(default=True, help_text='Is this timetable currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_district_timetables', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(help_text='Select the district this timetable belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='auth_app.district')),
            ],
            options={
                'verbose_name': 'District Timetable',
                'verbose_name_plural': 'District Timetables',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
