# Generated by Django 5.2.1 on 2025-10-21 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0028_churchcalendar_churchtimetable_collagecalendar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the writing/document', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the writing', null=True)),
                ('document', models.FileField(help_text='Upload document (PDF, Word, Excel, etc.)', upload_to='writings/')),
                ('document_type', models.CharField(choices=[('spiritual', 'Spiritual'), ('education', 'Education'), ('philosophy', 'Philosophy'), ('economy', 'Economy')], default='spiritual', help_text='Select the type of document', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Is this writing currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_writings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Writing',
                'verbose_name_plural': 'Writings',
                'ordering': ['-created_at'],
            },
        ),
    ]
