# Generated by Django 5.2.1 on 2025-11-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0029_writings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, help_text='Auto-generated username starting with UDOM_SDA_', max_length=150, unique=True, verbose_name='username'),
        ),
    ]
