# Generated by Django 5.2.1 on 2025-11-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0030_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, help_text='Auto-generated username starting with UDOM-SDA-', max_length=150, unique=True, verbose_name='username'),
        ),
    ]
