# Generated by Django 5.2.1 on 2025-11-14 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0031_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collagemembers',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collage_members', to='auth_app.church'),
        ),
        migrations.AlterField(
            model_name='collagemembers',
            name='collage_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='auth_app.collage'),
        ),
        migrations.AlterField(
            model_name='collagemembers',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collagemembers',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collage_members', to='auth_app.district'),
        ),
        migrations.AlterField(
            model_name='collagemembers',
            name='education_level',
            field=models.CharField(blank=True, choices=[('first_year', 'First Year'), ('second_year', 'Second Year'), ('third_year', 'Third Year'), ('fourth_year', 'Fourth Year'), ('fifth_year', 'Fifth Year'), ('sixth_year', 'Sixth Year')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='collagemembers',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collage_member_profiles', to='auth_app.members'),
        ),
        migrations.AlterField(
            model_name='collagemembers',
            name='nationality',
            field=models.CharField(blank=True, choices=[('tanzania', 'Tanzania'), ('kenya', 'Kenya'), ('uganda', 'Uganda'), ('rwanda', 'Rwanda'), ('burundi', 'Burundi'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='collagemembers',
            name='region',
            field=models.CharField(blank=True, choices=[('arusha', 'Arusha'), ('dar_es_salaam', 'Dar es Salaam'), ('dodoma', 'Dodoma'), ('geita', 'Geita'), ('iringa', 'Iringa'), ('kagera', 'Kagera'), ('katavi', 'Katavi'), ('kigoma', 'Kigoma'), ('kilimanjaro', 'Kilimanjaro'), ('lindi', 'Lindi'), ('manyara', 'Manyara'), ('mara', 'Mara'), ('mbeya', 'Mbeya'), ('morogoro', 'Morogoro'), ('mtwara', 'Mtwara'), ('mwanza', 'Mwanza'), ('njombe', 'Njombe'), ('pwani', 'Pwani'), ('rukwa', 'Rukwa'), ('ruvuma', 'Ruvuma'), ('shinyanga', 'Shinyanga'), ('simiyu', 'Simiyu'), ('singida', 'Singida'), ('tabora', 'Tabora'), ('tanga', 'Tanga')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='collagemembers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collage_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collagemembers',
            name='your_course',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='collagemembers',
            name='your_elder_from',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='collagemembers',
            name='your_origin_church',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='collagemembers',
            name='your_origin_district',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='collagemembers',
            name='your_secretary_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
