# Generated by Django 5.2.1 on 2025-11-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0032_alter_collagemembers_church_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, help_text='Auto-generated username starting with UDOM-ZONE-', max_length=150, unique=True, verbose_name='username'),
        ),
    ]
