# Generated by Django 5.2.1 on 2025-11-15 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0033_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry_name', models.CharField(max_length=200, unique=True)),
                ('services', models.TextField(help_text='Services offered by the ministry')),
                ('performance', models.DecimalField(decimal_places=2, help_text='Performance rating (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ministry',
                'verbose_name_plural': 'Ministries',
                'ordering': ['ministry_name'],
            },
        ),
        migrations.CreateModel(
            name='MinistryInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry_name', models.CharField(max_length=200)),
                ('services', models.TextField()),
                ('performance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ministry_members', models.TextField(blank=True, help_text='List of ministry members', null=True)),
                ('ministry_assets', models.TextField(blank=True, help_text='Assets owned by the ministry', null=True)),
                ('ministry_orders', models.TextField(blank=True, help_text='Current orders or projects', null=True)),
                ('costs_per_ministry', models.DecimalField(decimal_places=2, default=0.0, help_text='Total costs for this ministry', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('pdf_report', models.FileField(blank=True, help_text='PDF report for the ministry', null=True, upload_to='ministry_reports/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ministry Info',
                'verbose_name_plural': 'Ministry Infos',
                'ordering': ['-created_at'],
            },
        ),
    ]
