# Generated by Django 5.2.1 on 2025-11-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0034_ministry_ministryinfos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='performance',
            field=models.TextField(blank=True, help_text='Short description of performance', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ministryinfos',
            name='performance',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
