# Generated by Django 5.2.1 on 2025-11-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0035_alter_ministry_performance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='number_churches',
            field=models.PositiveIntegerField(default=0, help_text='Auto-calculated: Number of collages in this district'),
        ),
        migrations.AlterField(
            model_name='district',
            name='total_members',
            field=models.PositiveIntegerField(default=0, help_text='Auto-calculated: Total members across all collages'),
        ),
    ]
