# Generated by Django 5.2.1 on 2025-11-15 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0036_alter_district_number_churches_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collagemembers',
            name='church',
        ),
        migrations.RemoveField(
            model_name='members',
            name='church',
        ),
        migrations.RemoveField(
            model_name='churchcalendar',
            name='church',
        ),
        migrations.RemoveField(
            model_name='churchtimetable',
            name='church',
        ),
        migrations.DeleteModel(
            name='Church',
        ),
    ]
