# Generated by Django 5.2.1 on 2025-11-16 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0038_calendarevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='calendarevent',
            old_name='start_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='all_day',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='color',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='user',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='calendar_document',
            field=models.FileField(blank=True, null=True, upload_to='calendar_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='event',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='is_done',
            field=models.CharField(choices=[('pending', 'Pending'), ('on_process', 'On Process'), ('done', 'Done')], default='pending', max_length=20),
        ),
    ]
