# Generated by Django 5.2.1 on 2025-11-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0039_alter_calendarevent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_id', models.CharField(help_text='YouTube video ID (the part after v= in the URL)', max_length=50)),
                ('aspect_ratio', models.CharField(choices=[('16:9', '16:9 (Widescreen)'), ('4:3', '4:3 (Standard)'), ('21:9', '21:9 (Ultra Wide)'), ('1:1', '1:1 (Square)')], default='16:9', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'YouTube Video',
                'verbose_name_plural': 'YouTube Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
