# Generated by Django 5.2.1 on 2025-11-16 14:50

import auth_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0041_video_delete_youtubevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_file', models.ImageField(max_length=500, upload_to=auth_app.models.image_upload_path)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('file_format', models.CharField(blank=True, max_length=10)),
                ('dimensions', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'images',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='images_status_fc10b7_idx'), models.Index(fields=['uploaded_by', 'created_at'], name='images_uploade_76eedf_idx')],
            },
        ),
    ]
