# Generated by Django 5.2.1 on 2025-11-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0043_alter_image_uploaded_by'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='image',
            name='images_uploade_76eedf_idx',
        ),
        migrations.RemoveField(
            model_name='image',
            name='uploaded_by',
        ),
    ]
