# Generated by Django 5.2.1 on 2025-11-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0045_expensecategory_revenuesource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='record_type',
            field=models.CharField(choices=[('revenue', 'Revenue'), ('expense', 'Expense')], default='revenue', max_length=10),
        ),
    ]
