# Generated by Django 5.2.1 on 2025-11-19 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0046_financialrecord_record_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialrecord',
            name='record_type',
        ),
    ]
