# Generated by Django 5.2.1 on 2025-11-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0048_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='number_churches',
            field=models.PositiveIntegerField(default=0, help_text='Auto-calculated: Number of churches in this district'),
        ),
        migrations.AlterField(
            model_name='district',
            name='number_collages',
            field=models.PositiveIntegerField(default=0, help_text='Auto-calculated: Number of collages in this district'),
        ),
    ]
