# Generated by Django 5.2.1 on 2025-11-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0049_alter_district_number_churches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collage',
            name='collage_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='collage',
            name='total_members',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
