# Generated by Django 5.2.1 on 2025-11-29 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0050_alter_collage_collage_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APTEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='APTEC Name')),
                ('name_collage', models.CharField(max_length=100, verbose_name='College Name')),
                ('name_member', models.CharField(max_length=100, verbose_name='Member Name')),
                ('total_members', models.PositiveIntegerField(verbose_name='Total Members')),
                ('talent_member', models.TextField(help_text='List of talented members and their skills', verbose_name='Talented Members')),
                ('assets_owned', models.TextField(help_text='List of assets owned by APTEC', verbose_name='Assets Owned')),
            ],
            options={
                'verbose_name': 'APTEC',
                'verbose_name_plural': 'APTEC Groups',
            },
        ),
        migrations.CreateModel(
            name='APTEC_MISSION',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_mission', models.CharField(max_length=200, verbose_name='Mission Title')),
                ('description', models.TextField(verbose_name='Mission Description')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mission Cost')),
                ('success_expected', models.BooleanField(default=False, verbose_name='Success Expected')),
                ('location_expected', models.CharField(max_length=200, verbose_name='Expected Location')),
                ('list_members_expected', models.TextField(verbose_name='Expected Members List')),
                ('role_per_member', models.TextField(verbose_name='Role per Member')),
                ('success_reached', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('IN_PROGRESS', 'In Progress')], default='IN_PROGRESS', max_length=20, verbose_name='Success Reached')),
                ('assets_required', models.TextField(verbose_name='Assets Required')),
                ('aptec_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='auth_app.aptec', verbose_name='Associated APTEC Group')),
            ],
            options={
                'verbose_name': 'APTEC Mission',
                'verbose_name_plural': 'APTEC Missions',
            },
        ),
    ]
