# Generated by Django 5.2.1 on 2025-11-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0051_aptec_aptec_mission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aptec',
            name='assets_owned',
        ),
        migrations.RemoveField(
            model_name='aptec',
            name='total_members',
        ),
        migrations.AddField(
            model_name='aptec',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='mobile number of member'),
        ),
        migrations.AlterField(
            model_name='aptec',
            name='talent_member',
            field=models.TextField(help_text='talent of a member', verbose_name='Talent of member'),
        ),
    ]
