# Generated by Django 5.2.1 on 2025-11-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0052_remove_aptec_assets_owned_remove_aptec_total_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aptec_mission',
            name='location_expected',
            field=models.CharField(max_length=700, verbose_name='Expected Location'),
        ),
        migrations.AlterField(
            model_name='aptec_mission',
            name='success_expected',
            field=models.TextField(default=False, verbose_name='Success Expected'),
        ),
        migrations.AlterField(
            model_name='aptec_mission',
            name='success_reached',
            field=models.TextField(max_length=7000, verbose_name='Success Reached'),
        ),
    ]
