# Generated by Django 5.2.1 on 2025-12-01 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0053_alter_aptec_mission_location_expected_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialrecord',
            options={'ordering': ['-date'], 'verbose_name': 'Financial Record', 'verbose_name_plural': 'Financial Records'},
        ),
    ]
